### ISSUE TITLE
REQ: OpenHAB Hub Skill

### ISSUE THREAD

**Issue by confin234** [MycroftAI/mycroft-skills#162] opened 2017-09-26 20:57 UTC
Maybe we can make a skill that allows the Raspberry Pi or other computer inside a Mycroft device to act as an OpenHab hub, just like it would on a normal setup, except without a screen.

**Comment by el-tocino** [comment] 2017-09-26 21:06
I believe @btotharye is working on a homeassistant version.  Perhaps that would be close to what you're looking for?

**Comment by btotharye** [comment] 2017-10-04 19:36
closing duplicate of #48

**Closed by btotharye** 2017-10-04 19:36 UTC
Labels: Hacktoberfest
