### ISSUE TITLE
PiCroft - Skills Not Working on Fresh Install

### ISSUE THREAD

**Issue by tkoch96** [MycroftAI/mycroft-skills#398] opened 2018-06-09 16:13 UTC
Hello, 

I followed the instructions for installing Picroft on a Raspberry Pi here - https://mycroft.ai/documentation/picroft/#hardware-prerequisites
installing the 'stable' image for the pi.

Out of the box, the cli loads and I successfully pair it and everything, but basic skills don't work at all.

Example:
Hey Mycroft, what time is it?
I don't understand.

Hey Mycroft, what's the weather in san francisco?
I don't know what that means.

Upon restarting the skills service and looking at the skills log, it seems that certain python libraries are not getting imported (they are not being found and errors are being thrown). Why is this an issue on a fresh install and how should I go about fixing this?

**Comment by el-tocino** [comment] 2018-06-14 04:39
Have you installed anything as root?  Which version of picroft did you download?  Can you paste a relevant snippet of the log here as well?

**Comment by el-tocino** [comment] 2018-06-28 05:04
Closing for now, if still an issue reopen or file a new issue with the logs?

**Closed by el-tocino** 2018-06-28 05:04 UTC

**Comment by tkoch96** [comment] 2018-07-02 21:50
So the problem was that the skills were not being loaded correctly because python was running into errors such as 'library not found' and such. I had to go into sudo, activate the venv and install these libraries manually. Not a huge deal but still odd to have this problem on a fresh install. 
I think what ultimately caused these errors (and what made the problem very tough to solve) was that the code base is in between python versions so installing with pip or pip3 became a headache.

Sorry it took so long to answer.

**Comment by KathyReid** [comment] 2018-07-03 02:43
I also have a user who I've been helping who can't get Picroft to work on a fresh install. Their `mycroft-audio` service is throwing a bunch of `libvlc` errors, so I'll give this a try to see if that resolves things. Big thx @tkoch96 for letting us know what the cause / solution was.
