### ISSUE TITLE
Can't import multi_key_dict

### ISSUE THREAD

**Issue by beemorris** [MycroftAI/mycroft-skills#651] opened 2018-11-05 23:18 UTC
When trying to add new language to MyCroft, I get the error:
```
~~~~.348 - mycroft.skills.core:load_skill:117 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-weather.mycroftai with ID mycroft-weather.mycroftai
18:07:27.349 - mycroft.skills.core:load_skill:159 - ERROR - Failed to load skill: mycroft-weather.mycroftai
Traceback (most recent call last):
  File "/home/becca/mycroft-core/mycroft/skills/core.py", line 126, in load_skill
    imp.PY_SOURCE))
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 19, in <module>
    from multi_key_dict import multi_key_dict
ModuleNotFoundError: No module named 'multi_key_dict'
~~~~52 - mycroft.skills.core:load_skill:117 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-personal.mycroftai with ID mycroft-personal.mycroftai
```

I have multi_key_dict installed and have tried importing it in python, and it seems to work. Thanks!

**Comment by penrods** [comment] 2018-11-06 01:45
Several comments here:
1) What platform are you running under?
2) The https://github.com/MycroftAI/skill-weather/blob/18.08/requirements.txt _should_ have installed multi-key-dict, so I'm not sure how the skill got installed without it.
3) When you imported it, did you just use 'pip install multi-key-dict', or did you enter the Mycroft virtual environment first?  You can do that explicitly using "source venv-activate.sh" or by running the "mycroft-pip" script under the bin folder instead of just "pip".

Regardless, I'd like to understand the scenario that led to this issue.

**Comment by beemorris** [comment] 2018-11-07 23:27
Hello, thank you for your reply! It turns out I hadn't forked my own version of the skills repo into my fork of MyCroft. I have since done that and this is no longer an issue. Thank you!

**Comment by KathyReid** [comment] 2018-11-12 11:13
Thanks so much for confirming the issue isn't appearing anymore @beemorris, appreciate you closing the loop :+1:

**Closed as completed by KathyReid** 2018-11-12 11:13 UTC
